export const planosCriados = [
  {
    id: 1,
    title: "Matemática",
    description: "Equação do segundo grau",
    time: 45,
    about: "lorem ipsulum",
    nivel: "iniciante",
  },
  {
    id: 2,
    title: "Historia",
    description: "Segunda guerra mundial",
    time: 60,
    about: "lorem ipsulum",
    nivel: "Intermediario",
  },
  {
    id: 3,
    title: "Ciência",
    description: "Aquecimento global",
    time: 30,
    about: "lorem ipsulum",
    nivel: "iniciante",
  },
  {
    id: 4,
    title: "JavaScript",
    description: "Callback hell",
    time: 20,
    about: "lorem ipsulum",
    nivel: "intermediario",
  },
  {
    id: 5,
    title: "DSA",
    description: "Linked List",
    time: 25,
    about: "lorem ipsulum",
    nivel: "intermediario",
  },
];
